# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kaimi Kahihikolo
email: kaimibk@hawaii.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage for Kaimi Kahihikolo.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-149124828-1

github_username:  kaimibk
linkedin_username: kaimibk
avatar: https://avatars1.githubusercontent.com/u/20824806?s=400&u=035cd7c1d604d1a7ba8c9cc405d2359e7620721b&v=4

# Build settings
markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  Bayesian_Analysis:
    output: true
    title: Bayesian Analysis for the Logistical Sciences
    description: Notes on the book, _[Bayesian Logical Data Analysis for the Physical Sciences](https://www.amazon.com/Bayesian-Logical-Analysis-Physical-Sciences/dp/0521150124/ref=sr_1_fkmrnull_3?crid=1B8EBBP98CCSR&keywords=bayesian+logical+data+analysis+for+the+physical+sciences&qid=1558065973&s=gateway&sprefix=Bayesian+logical%2Caps%2C222&sr=8-3-fkmrnull)_ by Phil Gregory. These notes are not meant to be complete, just key information and examples from the text.
  Neural_Networks_and_Deep_Learning:
    output: true
    title: Neural Networks and Deep Learning
    description: Notes from the first course in the [Deep Learning Specialization](https://www.coursera.org/specializations/deep-learning) by Andrew Ng.
  Misc:
    output: true
    title: Miscellaneous Notes
    description: Miscellaneous notes from research papers, interesting articles, etc.
  Intro_Data_Science:
    output: true
    title: Introduction to Data Science Tutorials and Notes
    description: Miscellaneous tutorials and notes related to data science
  Outreach:
    output: false
    title: Outreach
  Research:
    output: false
    title: Research
