version: "3"
services:
    jekyll-serve:
        image: jekyll/jekyll:3.8
        container_name: jekyll-serve
        command: jekyll serve
        volumes:
            - ./vendor/bundle:/usr/local/bundle
            - .:/srv/jekyll
        environment:
            - JEKYLL_ENV=development
        ports:
            - 4000:4000